//! Parity with the Python oracle (`tests/golden/`, generated by
//! `scripts/gen_golden.py`).

use std::path::PathBuf;

use mstudio_core::skeleton::SkeletonModel;
use mstudio_core::{detect_outliers, Take};
use ndarray::{Array2, Array3};

fn golden(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../tests/golden").join(name)
}

fn manifest() -> serde_json::Value {
    serde_json::from_str(&std::fs::read_to_string(golden("manifest.json")).unwrap()).unwrap()
}

fn take_from_golden(frames_file: &str) -> Take {
    let m = manifest();
    let markers: Vec<String> =
        m["trc"]["markers"].as_array().unwrap().iter().map(|v| v.as_str().unwrap().to_string()).collect();
    let frames: Array3<f64> = ndarray_npy::read_npy(golden(frames_file)).unwrap();
    Take::new(markers, m["trc"]["fps"].as_f64().unwrap(), frames)
}

#[test]
fn skeleton_pairs_match_python_for_every_model_in_manifest() {
    let m = manifest();
    let take = take_from_golden("trc_frames.npy");
    for (model_name, pairs) in m["skeleton_pairs"].as_object().unwrap() {
        let model = SkeletonModel::by_name(model_name).unwrap_or_else(|| panic!("model {model_name}"));
        let expected: Vec<(String, String)> = pairs
            .as_array()
            .unwrap()
            .iter()
            .map(|p| (p[0].as_str().unwrap().to_string(), p[1].as_str().unwrap().to_string()))
            .collect();
        let got: Vec<(String, String)> = model
            .resolve_pairs(&take.markers)
            .into_iter()
            .map(|(a, b)| (take.markers[a].clone(), take.markers[b].clone()))
            .collect();
        assert_eq!(got, expected, "{model_name}");
    }
}

#[test]
fn outliers_match_python_for_every_model_clean_and_gapped() {
    let m = manifest();
    let threshold = m["outlier_threshold"].as_f64().unwrap();
    for (model_name, _) in m["skeleton_pairs"].as_object().unwrap() {
        for (frames_file, suffix) in [("trc_frames.npy", ""), ("trc_frames_gapped.npy", "_gapped")] {
            let file = golden(&format!("outliers_{model_name}{suffix}.npy"));
            if !file.exists() {
                continue; // models with no resolvable pairs have no golden
            }
            let take = take_from_golden(frames_file);
            let pairs = SkeletonModel::by_name(model_name).unwrap().resolve_pairs(&take.markers);
            let expected: Array2<u8> = ndarray_npy::read_npy(&file).unwrap();
            let got = detect_outliers(&take.frames, &pairs, threshold).mapv(|b| b as u8);
            assert_eq!(got, expected, "{model_name}{suffix}");
        }
    }
}

#[test]
fn rename_markers_maps_keypoint_ids_to_halpe26_names() {
    let n = 26;
    let markers: Vec<String> = (0..n).map(|i| format!("Keypoint_{i}")).collect();
    let mut take = Take::new(markers, 30.0, Array3::zeros((2, n, 3)));
    assert!(take.rename_markers(&mstudio_core::skeleton::HALPE_26));
    // HALPE_26: id 19 is Hip (the root), id 0 is Nose
    assert_eq!(take.markers[19], "Hip");
    assert_eq!(take.markers[0], "Nose");
    assert!(!take.has_generic_names());
    assert!(!take.rename_markers(&mstudio_core::skeleton::HALPE_26));
}
