#!/usr/bin/env python
"""
Generate crates/mstudio-core/src/skeleton_tables.rs from MStudio/utils/skeletons.py.

The Python module (vendored from Pose2Sim, BSD-3, David Pagnon) defines every
skeleton as an anytree hierarchy. This script flattens each tree in pre-order
into a static Rust table so the Rust port cannot drift from the oracle by hand
transcription. Re-run whenever skeletons.py changes:

    .venv/bin/python scripts/gen_skeletons.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from anytree import Node  # noqa: E402

from MStudio.utils import skeletons  # noqa: E402

# Order matches TRCViewer.available_models (the models the app offers).
APP_MODELS = ["BODY_25B", "BODY_25", "BODY_135", "BLAZEPOSE", "HALPE_26", "HALPE_68", "HALPE_136", "COCO_133", "COCO", "MPII", "COCO_17"]

OUT = ROOT / "crates" / "mstudio-core" / "src" / "skeleton_tables.rs"
OUT.parent.mkdir(parents=True, exist_ok=True)

models = [(name, obj) for name, obj in vars(skeletons).items() if isinstance(obj, Node) and name.isupper()]
models.sort(key=lambda kv: kv[0])

lines = [
    "//! GENERATED by scripts/gen_skeletons.py from MStudio/utils/skeletons.py",
    "//! (Pose2Sim skeleton definitions, BSD-3-Clause, David Pagnon). Do not edit by hand.",
    "",
    "use crate::skeleton::{Node, SkeletonModel};",
    "",
]
for name, root in models:
    nodes = [root] + list(root.descendants)  # anytree descendants are pre-order
    index = {id(n): i for i, n in enumerate(nodes)}
    lines.append(f"pub static {name}: SkeletonModel = SkeletonModel {{")
    lines.append(f'    name: "{name}",')
    lines.append("    nodes: &[")
    for n in nodes:
        nid = getattr(n, "id", None)
        id_s = "None" if nid is None else f"Some({int(nid)})"
        parent_s = "None" if n.parent is None else f"Some({index[id(n.parent)]})"
        lines.append(f'        Node {{ name: "{n.name}", id: {id_s}, parent: {parent_s} }},')
    lines.append("    ],")
    lines.append("};")
    lines.append("")

lines.append("/// Every skeleton defined in skeletons.py, alphabetical.")
lines.append("pub static ALL_MODELS: &[&SkeletonModel] = &[" + ", ".join(f"&{n}" for n, _ in models) + "];")
lines.append("")
lines.append("/// The models the application offers in its skeleton combo box, in UI order.")
lines.append("pub static APP_MODELS: &[&SkeletonModel] = &[" + ", ".join(f"&{n}" for n in APP_MODELS) + "];")
lines.append("")

OUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {OUT.relative_to(ROOT)}: {len(models)} models, {sum(1 + len(r.descendants) for _, r in models)} nodes")
